image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 12

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - npm run build
